check:
  - thoth-build
build:
  base-image: "registry.access.redhat.com/ubi7/python-38"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "odh-jupyterhub"
  registry-project: "jupyterhub"
  registry-secret: "odh-jupyterhub-thoth-pusher-secret"
